spring.application.name=HighlightShare

server.port=8080
server.servlet.context-path=/

spring.datasource.url=jdbc:postgresql://localhost:5432/highlightshare
spring.datasource.username=postgres
spring.datasource.password=${PG_SECRET:12345}

spring.jpa.hibernate.ddl-auto = update
#spring.jpa.properties.hibernate.default_schema = pessoa

logging.level.org.hibernate.SQL = debug
logging.level.org.hibernate.type.descriptor.sql.BasicBinder = trace
logging.level.org.springframework.security=DEBUG

api.security.token.secret=${JWT_SECRET:my-secret-key}

springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

